# Generated by Django 2.1.3 on 2019-03-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hire_Producer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('producer_name', models.CharField(max_length=100)),
                ('hire_date', models.DateField()),
                ('hire_time', models.TimeField()),
                ('duration_days', models.IntegerField(default=0)),
                ('duration_hrs', models.IntegerField(default=0)),
                ('available_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Music_Artist_Sessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('start_date', models.DateField()),
                ('starting_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Producer_Sessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('start_date', models.DateField()),
                ('starting_time', models.TimeField()),
            ],
        ),
    ]
