# Generated by Django 2.1.3 on 2019-03-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioSessions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fullName', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=13)),
                ('booked_as', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('starting_time', models.TimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Music_Artist_Sessions',
        ),
        migrations.DeleteModel(
            name='Producer_Sessions',
        ),
    ]
