# Generated by Django 2.1.3 on 2019-03-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190319_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hire_producer',
            name='available_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hire_producer',
            name='hire_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hire_producer',
            name='hire_time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studiosessions',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studiosessions',
            name='starting_time',
            field=models.CharField(max_length=100),
        ),
    ]
