# Generated by Django 2.1.3 on 2019-03-20 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190320_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hire_producer',
            name='available_date',
        ),
        migrations.RemoveField(
            model_name='hire_producer',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='hire_producer',
            name='duration_hrs',
        ),
        migrations.RemoveField(
            model_name='hire_producer',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='hire_producer',
            name='hire_time',
        ),
        migrations.RemoveField(
            model_name='hire_producer',
            name='producer_name',
        ),
        migrations.RemoveField(
            model_name='studiosessions',
            name='booked_as',
        ),
        migrations.RemoveField(
            model_name='studiosessions',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='studiosessions',
            name='starting_time',
        ),
    ]
