# Generated by Django 2.1.3 on 2019-03-20 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20190320_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='hire_producer',
            name='available_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hire_producer',
            name='duration_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hire_producer',
            name='duration_hrs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hire_producer',
            name='hire_date',
            field=models.CharField(default=datetime.datetime(2019, 3, 20, 16, 40, 21, 43915, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hire_producer',
            name='hire_time',
            field=models.CharField(default=datetime.datetime(2019, 3, 20, 16, 40, 41, 484006, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hire_producer',
            name='producer_name',
            field=models.CharField(default=datetime.datetime(2019, 3, 20, 16, 41, 1, 677833, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiosessions',
            name='booked_as',
            field=models.CharField(default=datetime.datetime(2019, 3, 20, 16, 41, 14, 304494, tzinfo=utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiosessions',
            name='start_date',
            field=models.CharField(default=datetime.datetime(2019, 3, 20, 16, 41, 45, 517537, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studiosessions',
            name='starting_time',
            field=models.CharField(default=datetime.datetime(2019, 3, 20, 16, 42, 4, 246856, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
