# Generated by Django 2.1.3 on 2019-03-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190320_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiosessions',
            name='booked_as',
            field=models.CharField(choices=[('producer', 'producer'), ('other', 'other')], default='other', max_length=20),
        ),
    ]
