# Generated by Django 2.1.3 on 2019-03-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20190320_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiosessions',
            name='booked_as',
            field=models.CharField(choices=[('Producer', 'Producer'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
