# Generated by Django 2.1.3 on 2019-03-21 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20190321_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studiosessions',
            name='starting_time',
        ),
    ]
