# Generated by Django 2.1.3 on 2019-03-21 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20190321_1718'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudioSessions',
            new_name='StudioSession',
        ),
    ]
