# Generated by Django 2.1.3 on 2019-03-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20190321_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('comment', models.CharField(max_length=500)),
                ('comment_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
