# Generated by Django 2.1.3 on 2019-03-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment',
        ),
    ]
