# Generated by Django 2.1.3 on 2019-03-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_comment_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='this was the first comment', max_length=500),
            preserve_default=False,
        ),
    ]
