# Generated by Django 2.1.3 on 2019-03-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20190322_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
