# Generated by Django 2.1.3 on 2019-03-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_auto_20190322_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiosession',
            name='start_date',
            field=models.DateField(max_length=100),
        ),
    ]
