# Generated by Django 2.1.3 on 2019-03-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20190323_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studiosession',
            name='start_date',
            field=models.DateField(),
        ),
    ]
