# Generated by Django 2.2 on 2019-05-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_remove_hireproducer_producer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Music_Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100)),
                ('booked_as', models.CharField(choices=[('Producer', 'Producer'), ('Artist', 'Artist')], default='Artist', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Short_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100)),
                ('course', models.CharField(choices=[('Music Production', 'Music_Production'), ('Instruments', 'Instruments')], default='Music Production', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Studio_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=100)),
                ('booked_as', models.CharField(default='Producer', max_length=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='HireProducer',
        ),
        migrations.DeleteModel(
            name='StudioSession',
        ),
    ]
